worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream python_backend {
        server host.docker.internal:8181 max_fails=0;
        server host.docker.internal:8182 max_fails=0;
    }

    server {
        listen 80;

        location /my-service/health {
            proxy_pass http://python_backend/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
